import type { NextPage } from "next";
import Link from "next/link";
import Navbar from "../Components/navbar";
import styled from "styled-components";
import Image from "next/image";
import React from "react";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Container>
      <section className="vh-100">
        <Head>
          <title>Serve.me</title>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossOrigin="anonymous"
          ></script>
          <meta charSet="utf-8" />
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossOrigin="anonymous"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <NavBar className="navbar navbar-expand-md navbar-dark bg-nav fixed-top rounded-manual">
          <div className="container-fluid">
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon" />
            </button>
            <Link href="/">
              <a className="navbar-brand">Serve.me</a>
            </Link>
            <Link href="/">
              <a className="navbar-brand"></a>
            </Link>
            <InnerContainer
              className="collapse navbar-collapse show"
              id="navbarSupportedContent"
            >
              <ul className="navbar-nav me-auto mb-2 mb-lg-0 center-me">
                <li className="nav-item justify-content-center">
                  <Image 
                    src="/formanek1.jpg"
                    width={100}
                    height={100}
                    className="headImg"

                  />
                </li>
                <li className="nav-item justify-content-center">
                  <Link href="/">
                    <a href="#" className="nav-link active nav-text">
                      <Bordered>Jiří FORMÁNEK</Bordered>
                    </a>
                  </Link>
                </li>
                <li className="nav-item justify-content-center distance">
                </li>
                <li className="nav-item justify-content-center">
                  <Link href="/">
                    <a href="#" className="nav-link active small-black">
                      Osobní údaje
                    </a>
                  </Link>
                </li>
                <li className="nav-item justify-content-center">
                  <Link href="/">
                    <a href="#" className="nav-link active small-black">
                      Změna hesla
                    </a>
                  </Link>
                </li>
              </ul>
              <User className="center">

                <Link href="/logout">
                  <a href="#" className="d-flex nav-item nav-link">
                    <button type="button" className="btn btn-light red btn-lg">
                      ODHLÁSIT SE
                    </button>
                  </a>
                </Link>
              </User>
            </InnerContainer>
          </div>
        </NavBar>
      </section>
    </Container>
  );
};

export default Home;

const NavBar = styled.nav`
  padding-bottom: 0px;
  .headImg {
      border-radius: 50%;
  }
  .container-fluid {
    padding-left: 0px;
    padding-right: 0px;
  }
  .container-fluid button {
    margin-left: 5vw;
  }
  .navbar-brand {
    margin-right: 2.2 rem;
  }
  .show {
    height: 85vh;
  }
  .small-black {
      color: black !important;
      font-size: 18px
  }
  border-radius: 0% 0% 5vw 5vw;
  .red {
      background-color:#CF0000;
      color: white;
      font-size:18px;
  }
`;
const InnerContainer = styled.div`
  background-color: white;
  border-radius: 5vw;
  .nav-text {
    color: red !important;
  }

  .center-me {
    justify-content: center;
    align-items: center;
    height: 60%;
  }
  
`;
const User = styled.div`
  margin-top: 20vh;
  display: flex;
  justify-content: center;
  align-items: center;
  bottom: 10vw;
  a button {
    margin-left: 0px !important;
    background-color: white;
    color: red;
    box-shadow: 0 3px 10px -5px rgba(0, 0, 0, 0.8);
  }
`;
const Container = styled.div``;
const Bordered = styled.div`
    border: 1px solid rgba(0,0,0,0.4);
    font-weight: bold; 
    border-radius: 20px; 
    width: auto; 
    height: auto; 
    padding: 3px 20px 3px 20px; 
`;
