import React, {  useState } from "react"
import { onAuthStateChanged, signInWithEmailAndPassword, signOut} from "firebase/auth"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'  
import{auth} from "../utils/firebase"
import Navbar from "./Components/Navbar"


const Login=()=>{

    const[loginEmail, SetLoginEmail] = useState("");
    const[loginPassword, SetLoginPassword] = useState("");
    
    const[user,SetUser] = useState<object | null >({});
    

    onAuthStateChanged(auth, (curentUser) =>{
        SetUser(curentUser);
    })


    const login = async () =>{
        try{
            const user = await signInWithEmailAndPassword(auth, loginEmail, loginPassword);
            console.log(user);
        }catch(error : any){
            console.log(error.message)
        }
    }

    const logOut = async () =>{

        await signOut(auth);
    }

    return(
        <div>
          <Head>
                <title>Serve.me</title>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
                <meta charSet="utf-8" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous" />
                <link rel="icon" href="/favicon.ico" /> 
                <link rel="stylesheet" href="styles/base.css" />
            </Head>
          <Navbar/>
            <section className="vh-100">
        <div className="container-fluid h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col-md-9 col-lg-6 col-xl-5">
            </div>
            <div className="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <form>
                <div className="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
                  <p className="lead fw-normal mb-0 me-3 title">Sign in</p>
                </div>
                <div className="divider d-flex align-items-center my-4">
                  <p className="text-center fw-bold mx-3 mb-0" />
                </div>
                <div className="form-outline mb-4 input">
                  <input type="email" id="form3Example3" className=" input-field"  onChange={(event)=>{
                        SetLoginEmail(event.target.value)
                    }}
                required/>
                  <label className="form-label input-label" htmlFor="form3Example3">Email address</label>
                </div>
                <div className="form-outline mb-3 input">
                  <input type="password" id="form3Example4" className=" input-field"  onChange={(event)=>{
                        SetLoginPassword(event.target.value)
                    }}
                required/>
                  <label className="form-label input-label" htmlFor="form3Example4">Password</label>
                </div>
                {/* <div className="d-flex justify-content-between align-items-center">
                  <div className="form-check mb-0">
                    <input className="form-check-input me-2" type="checkbox" defaultValue id="form2Example3" />
                    <label className="form-check-label" htmlFor="form2Example3">
                      Remember me
                    </label>
                  </div>
                  <a href="#!" className="text-body">Forgot password?</a>
                </div> */}
                <div className="text-center text-lg-start mt-4 pt-2 d-grid gap-2">
                  <button type="button" className="btn btn-danger btn-lg boton" style={{paddingLeft: '5rem', paddingRight: '5rem'}} onClick={login}>Login</button>
                  {/* <p className="small fw-bold mt-2 pt-1 mb-0">Don't have an account?<Link href="register"><a href="#" className="link-danger"> Register</a></Link></p> */}
                </div>
              </form>
            </div>
          </div>
        </div>
        
      </section>
            {/* <h4>User signed in: </h4>
            {
                //@ts-ignore: Object is possibly 'null'
                user?.email
            }

            <button onClick={logOut}>Sign out</button>
        </div> */}
         {/* <div className="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary fixed-bottom">
          <div className="text-white mb-3 mb-md-0">
            Copyright Serve.me 2021
          </div>
          
      </div>  */}
        </div> 
    )
}
export default Login;